### ISSUE TITLE
创建群聊时，群头像是默认的，获取群聊详情时没有对应的avatar字段，是否需要添加一个默认的头像链接？

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#162]
- 添加

  便于用户直接拿到avatar内容，不用做非空判断

- 不添加

  用户做非空判断后，可以自行设置默认头像

> 个人认为添加默认头像链接比较好，avatar为空不太合理。

**Comment by bung87** [comment]
没有拿到就是没有拿到，作为一个库来说不希望有默认头像，不一定符合用户的产品设计。

**Comment by guo40020** [comment]
avatar应该为空，给使用者更多的定制空间而不是要来改puppet

**Comment by hcfw007** [comment]
如果就用默认的头像图片做成链接呢？

**Comment by windmemory** [comment]
从开发体验上来讲，应该没人在意默认头像，也不会有人想要自定义默认头像。所以如果不同的puppet都能提供各自不同的默认头像，应该是最好的。
但是从灵活性上讲，返回空是最好的，但是空头像的存在，无疑给开发者增加了额外的负担，需要处理这种头像的情况，并且自己找一个默认头像。

我觉得可能想要自定义默认头像的真实场景概率很低，所以投自带默认头像一票~

**Comment by hcfw007** [comment]
issue有投票功能吗...我是支持留空的...

**Comment by windmemory** [comment]
> > 从开发体验上来讲，应该没人在意默认头像，也不会有人想要自定义默认头像。所以如果不同的puppet都能提供各自不同的默认头像，应该是最好的。 但是从灵活性上讲，返回空是最好的，但是空头像的存在，无疑给开发者增加了额外的负担，需要处理这种头像的情况，并且自己找一个默认头像。
> > 我觉得可能想要自定义默认头像的真实场景概率很低，假设我自己在用wechaty做机器人的话，我会投自带默认头像一票，因为很省事
> 
> 但是其实也没有增加什么负担吧，毕竟ts就是加两个问号的事情

增加的负担是，我得去找个头像……还挺费事的……

**Comment by su-chang** [comment]
结论：暂不设置默认头像，如果联系人/群组没有头像，则avatar字段为 `undefined`
