### ISSUE TITLE
roomCreate fails for android users due to don't have reliable isMyContact

### ISSUE THREAD

**Issue by bung87** [wechaty/puppet-whatsapp#170]
## 1. Versions

`wechaty-puppet-0.41.9`

## 2. Describe the bug

https://github.com/wechaty/puppet-whatsapp/blob/acb872456a4553d7db484486fb0d228dc33f85e5/src/puppet-mixins/room.ts#L86  

in `src/puppet-mixins/room.ts` `checkRoomMember` filter out `friendList` and `nonFriendsList` depends on `isMyContact` however for android user we don't have reliable value, in my case I saved coworkers to my contact, `isMyContact` is always false, like in `contactRawPayloadParser` I use `contactPayload.isWAContact` to identify friend, otherwise I don't have any friend. note: `isMyContact` works on ios.

so here `friendsList` always empty, create room will fails and cause `exception: You need to add at least one other participant to the group`

**Comment by su-chang** [comment]
需要仔细考虑并设计下 friend 的判断依据。需要着重针对不同操作系统进行测试。

**Comment by bung87** [comment]
result it causes by whatsapp read contact permission on android.

**Comment by su-chang** [comment]
> result it causes by whatsapp read contact permission on android.

@bung87  Maybe we should add this recommendation on `MiaoHui` QR code page. How do you think about that?

**Comment by bung87** [comment]
yeah, I agree
