### ISSUE TITLE
入群事件，接收到的id为联系人id

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#188]
```
22:34:33 INFO PuppetWhatsApp room roomMemberList(8613126768525@c.us)
22:34:33 VERB FlashStore get(8613126768525@c.us)
22:34:33 ERR errorListener Error happened:
undefined
```

**Comment by huan** [comment]
A unit test should be added to prevent the future bugs like this.

**Comment by su-chang** [comment]
> A unit test should be added to prevent the future bugs like this.

Done, thank you for your suggestion.

**Comment by huan** [comment]
@su-chang You are awesome! (And the unit tests too!)
