### ISSUE TITLE
messageforward没有正确返回新message的id

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-whatsapp#192]
而是返回了void

**Comment by huan** [comment]
## Anti-pattern warning

Please notice that return a message id when sending a message is treated as an anti-pattern in Wechaty.

The returned type of all kind of the `messageSendXXX` are recommended to be `void`.

This is also a design pattern when we implementing the CQRS (Command Query Responsibility Segregation) pattern.

**Comment by hcfw007** [comment]
> ## Anti-pattern warning
> Please notice that return a message id when sending a message is treated as an anti-pattern in Wechaty.
> 
> The returned type of all kind of the `messageSendXXX` are recommended to be `void`.
> 
> This (return void) is also a design pattern when we implementing the CQRS (Command Query Responsibility Segregation) pattern.
> 
> CC @wechaty/juzi

But in wechaty-puppet v0.40, the return type of messageForward is Promise<void | string>
https://github.com/wechaty/puppet/blob/98a4aac9acb799865d0585f1d05cbb7584a69db3/src/puppet.ts#L821

**Comment by huan** [comment]
Yes, that's a workaround.

Please keep in mind that we should use `void` when possible as a best practice.

And also, do not forget to check the return value existence (might be `undefined` according to the definition) when using Wechaty API.

**Comment by windmemory** [comment]
We have a feature needs to be implemented that we want to track a message source sent out from our system. For example, one message can be sent by user manually input (we call it console), but it also can be sent out by system automatically (we call it bot). We would like to know the source of the message, so we need the message id when we sending the message.

To resolve the problem and fit the CQRS pattern, I think a good design is to add a `trackingData` field when we send a message. After the message is sent, `Wechaty` emitted a new message with the `trackingData` when we sent out the message, then we can map the sent message with the original sent operation, then we can know the message source for the sent message.

@huan does this make sense to you?

**Comment by huan** [comment]
Yes, the reason that we should not depends on the return value is that we want to follow the CQRS design pattern: Command should be separate to the Query.

For now, we can continue using the current return value as workaround.

Let's keep the CQRS in mind for the future design, because the final solution still need to be decided.

**Comment by hcfw007** [comment]
It turns out we cannot get the id of the forwarded message with whatsapp-web.js.
