### ISSUE TITLE
WhatsApp web api 测试及整理对应的数据结构

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#20]
- [x] 测试whatsapp-web.js接口，并整理对应的请求参数及响应结果的数据结构。
- [x] 基于整理的数据结构构建对应的 ts model。
- [x] 整理测试过程中遇到的卡点（困难点），进行讨论分析。

**Comment by wedreamer** [comment]
- 激进的时间预估 2022-1-10
- 保守的时间预估 2022-1-11

**Comment by wedreamer** [comment]
https://github.com/wechaty/puppet-whatsapp/pull/35
