### ISSUE TITLE
封装 request 类，处理所有api请求

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#21]
- [x] 构建公共基础请求类
- [ ] 定义各个请求的枚举类型
- [ ] 将请求和响应进行匹配（类似trace等手段，目前还不清楚whatsapp本身是否支持该功能）

**Comment by hcfw007** [comment]
预计完成时间：1.9 - 1.12

**Comment by huan** [comment]
I think this is a very strange layer and I can not understand why we need it.

**Comment by su-chang** [comment]
The aim for control all requests related `WhatsApp` in one class, e.g.

- match request and response
- add rate queue for some requests
- other services could call request methods in this class with `type` and `params`

**Comment by huan** [comment]
@su-chang Thanks for the explanation.

I think what you described is very like the Wechaty Redux layer, you can have a look at https://github.com/wechaty/redux/blob/main/src/duck/actions.ts .

Please feel free to go ahead and keep me updated, thanks.

**Comment by hcfw007** [comment]
#36

**Comment by hcfw007** [comment]
任务二 定义各个请求的枚举类型 是否是个实际的需求？因为并非通过API.Type进行调用。 @su-chang

**Comment by hcfw007** [comment]
任务三 将请求和响应进行匹配 应该也并不需要，因为所有请求本身都会返回包含结果的Promise

**Comment by su-chang** [comment]
> 任务二 定义各个请求的枚举类型 是否是个实际的需求？因为并非通过API.Type进行调用。 @su-chang

不是实际需求，当时只是大致的一个想法，具体按实际需要来定。

**Comment by su-chang** [comment]
> 任务三 将请求和响应进行匹配 应该也并不需要，因为所有请求本身都会返回包含结果的Promise

如果是这样的话，最好了。我们可以省去一些不必要的匹配代码。
但是目前还是处于存疑状态，需要看看后续是否会有一些请求的响应结果中没有包含我们所需要的信息而是需要从回调中获取的情况。

**Comment by hcfw007** [comment]
#40
