### ISSUE TITLE
接入 flash-store 做 contact / room / message 的缓存

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#22]
> 需要缓存 raw data

- [ ] contact 联系人/好友的缓存 （二者可能数据结构有所不同，应该有一个base类型）
- [ ] room 群组的缓存
- [ ] message 消息的缓存
- [ ] 确认各缓存的生存周期以及清除策略

**Comment by huan** [comment]
Here we have a flash-store cache class using by the Puppet Service module, which I believe can be generalized:

https://github.com/wechaty/puppet-service/blob/main/src/client/payload-store.ts

Just FYI.

**Comment by su-chang** [comment]
> Here we have a flash-store cache class using by the Puppet Service module, which I believe can be generalized:

I will have a try, thanks for your suggestions.

**Comment by huan** [comment]
You are welcome

**Comment by su-chang** [comment]
- 激进的时间预估 2022-01-13
- 保守的时间预估 2022-01-14

**Comment by su-chang** [comment]
延期至 2022-01-20
