### ISSUE TITLE
room 功能进行实现

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#25]
- [x] 根据 whatsapp 现有 api，挑选出与群聊相关的操作进行实现
- [x] 针对群操作相关的功能需要将其转换成对应的群事件（room-join, room-leave, room-invite, room-topic）

**Comment by bung87** [comment]
激进的时间预估 2022-01-14
保守的时间预估 2022-01-18

**Comment by bung87** [comment]
1-10 done

**Comment by huan** [comment]
It would be better to link the related code PR to its issue because it can link the knowledge together for future reviews.

**Comment by windmemory** [comment]
@bung87 Could you please add the PR link to this issue?

**Comment by bung87** [comment]
https://github.com/wechaty/puppet-whatsapp/pull/18
