### ISSUE TITLE
message 功能进行实现

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#26]
- [x] 整理所有发送消息的类型
- [x] #48
- [x] 注意媒体文件的发送及对应素材的管理及缓存

**Comment by socialok** [comment]
这个好像还木有放时间

**Comment by guo40020** [comment]
> 这个好像还木有放时间

现在放了

**Comment by guo40020** [comment]
## 整理了一些问题
1. throw new Error会导致问题吗
2. WhatsApp对链接没有标题支持，目前返回链接内容时标题传空
3. WhatsApp支持发送多联系人名片，但是根据puppet抽象层返回类型，获取联系人名片只能返回一个。  
   目前只返回第一个，应该格式化字符串返回吗，或者返回json？

**Comment by bung87** [comment]
原则上是以实现puppet的现有接口为准。
2， 没有标题传空字符串
3， puppet 只需要一个联系人id 就只发送一个

**Comment by windmemory** [comment]
> ## 整理了一些问题
> 1. throw new Error会导致问题吗
> 2. WhatsApp对链接没有标题支持，目前返回链接内容时标题传空
> 3. WhatsApp支持发送多联系人名片，但是根据puppet抽象层返回类型，获取联系人名片只能返回一个。
>    目前只返回第一个，应该格式化字符串返回吗，或者返回json？
>    @socialok

1. 如果是预期意外的问题出现了，那么throw error不会有问题，就应该throw error
2. 返回空应该没啥问题，不过如果能直接从链接里抓出来标题就最好了（可以参考下UrlLink里面的实现，记得有基于facebook的一个标准规范去网页里面抓了标题，描述和缩略图）
3. 这个可能需要提一个RFC到wechaty的主repo，讨论一下这种情况如何来支持。或许需要更改一下puppet上的方法
@guo40020

**Comment by guo40020** [comment]
## 名片问题
`msg.vCards`获取到的联系人名片内容是没有经过解析的，即：
```
BEGIN:VCARD
VERSION:3.0
N:;Yuan Gao;;;
FN:Yuan Gao
item1.TEL;waid=8613947519555:+86 139 4751 9555
item1.X-ABLabel:‎WhatsApp
END:VCARD
```
---
### Q:
- 应该取手机号还是waid？
- 是否需要Name？怎么传？

**Comment by su-chang** [comment]
> 3\. WhatsApp支持发送多联系人名片，但是根据puppet抽象层返回类型，获取联系人名片只能返回一个。
>     目前只返回第一个，应该格式化字符串返回吗，或者返回json？

@guo40020 关于这个可以补充在 https://github.com/wechaty/puppet-whatsapp/issues/23 这里，并在wechaty中提RFC。

**Comment by bung87** [comment]
lack implemented apis:  
1. message forward. 

https://github.com/wechaty/puppet/blob/e009523748da67ef05b4af5d6c1f7105b6a597fe/docs/typedoc/classes/puppet.md#abstract-messageforward

https://github.com/pedroslopez/whatsapp-web.js/blob/46ba9c5e9aa0bc4de5eba1a561e7f4ef8050084a/src/structures/Message.js#L313

2. messageRecall. 

https://github.com/wechaty/puppet/blob/efcf69183612bf12266f8504466eb43c2dca2590/src/mixins/message-mixin.ts#L70

https://github.com/pedroslopez/whatsapp-web.js/blob/46ba9c5e9aa0bc4de5eba1a561e7f4ef8050084a/src/structures/Message.js#L381
