### ISSUE TITLE
Checklist for merging v0.41 branch to main

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-whatsapp#263]
### 1. Basic setup

- [x] #261 

### 2. Add basic helper classes

- [x] #262
- [x] #267
- [x] #268
- [x] #270

### 3. WhatsApp functionality

- [x] #264
- [x] #271
- [x] #272
- [x] #281
- [x] #282

### 4. Other optimization
- [x] bug fix - ding-dong-bot works!
  - [x] #309 
  - [x] #317 
  - [x] #318 
  - [x] #319
  - [x] #321 
  - [x] #320
- [x] #312
- [x] add unit test
  - [x] #304
  - [x] #306
  - [x] #316
  - [x] #302
  - [x] #308

**Comment by su-chang** [comment]
Cheers! And let's merge it to `main` now.

**Comment by huan** [comment]
Congratulations!

**Comment by su-chang** [comment]
Happy to see: https://github.com/wechaty/puppet-whatsapp/pull/322 has been merged. Let's close this issue now. @hcfw007
