### ISSUE TITLE
登录/登出状态管理

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#27]
- [x] 登录状态转换为对应的login事件
- [x] 登录后做一些相关初始化的操作
- [x] 登出状态转换为对应的logout事件
- [x] 登出后做一些资源释放的相关操作
- [x] 保持登录状态一致性

**Comment by wedreamer** [comment]
- 激进的时间预估 2022-1-17
- 保守的时间预估 2022-1-18

**Comment by bung87** [comment]
https://github.com/wechaty/puppet-whatsapp/pull/41
