### ISSUE TITLE
重新梳理项目目录结构，方便大家协作开发

### ISSUE THREAD

**Issue by windmemory** [wechaty/puppet-whatsapp#31]
- [x] 创建单独缓存管理类（对应缓存相关功能）
- [x] 创建请求类（对应request相关功能）
- [ ] 创建实现类（对应contact，message和room相关功能，可以酌情考虑将三种功能分别放在不同的文件或类里管理，参考mixin的方式）

**Comment by su-chang** [comment]
- 激进的时间预估 2022-01-10
- 保守的时间预估 2022-01-11

**Comment by su-chang** [comment]
关于创建实现类，使用mixins方式来处理会当做一个新的任务来处理。

**Comment by su-chang** [comment]
> 关于创建实现类，使用mixins方式来处理会当做一个新的任务来处理。

https://github.com/wechaty/puppet-whatsapp/issues/40
