### ISSUE TITLE
Can not get QR Code for login with v1.15

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-whatsapp#328]
It seems that we are emitting the `scan` event payload incorrectly:

https://github.com/wechaty/puppet-whatsapp/blob/bdfa32ea8e2ab4c7be01c0ed90e1c33b87597025/src/whatsapp/event-handler/login-event-handler.ts#L36-L40

According to the above code, the typing of the payload is `status: PUPPET.payloads.EventScan, url?: string | undefined` but we provided `qr`.

Which I believe is the reason that I got the below log messages:

```
19:35:24 INFO WechatyPluginContrib EventLogger scan: ,[object Object],
19:35:34 INFO LoginEventHandler onQRCode(1@VO2AyDojV7zfX3eE5MMtuxSLGWgfN/ZaAfqsvDl6bYUSTC+9WTYP1SKpPJP42X6yecvjBJRH+st0Bw==,Lij20FMqgUFnEfQdRG/Wss9bFzaB/G31V3bQH07QyAI=,DsmQp2crK1L9f+1P9GnNew==)
19:35:34 VERB PuppetWhatsapp onScan([object Object], undefined)
19:35:34 INFO PuppetWhatsapp SCAN
```

And according to the below code:

https://github.com/wechaty/puppet-whatsapp/blob/bdfa32ea8e2ab4c7be01c0ed90e1c33b87597025/src/puppet-whatsapp.ts#L175-L180

We can confirm that the `status` and `qrcode` from `'onScan(%s, %s)', status, qrcode` are both incorrect.

@su-chang @hcfw007

**Comment by su-chang** [comment]
Thank you for describing this bug, it help me to resolve it quickly. It could be resolved after `1.15.1`.

**Comment by huan** [comment]
You are welcome.

I'm curious about why the typing system (TypeScript) has not prevent this bug.

**Comment by hcfw007** [comment]
Somehow xiaoju-bot and puppet-whatsapp@0.41 works. Will check corresponding code.

**Comment by huan** [comment]
Please let me know when we have any updates, thank you very much!

**Comment by su-chang** [comment]
> I'm curious about why the typing system (TypeScript) has not prevented this bug, and how could this happen after we have finished testing the v0.41?

```
{
  status: {
    status: 2,
  },
}
```
Maybe it seems that typescript regard this data as PUPPET.payloads.EventScan?

> Somehow xiaoju-bot and puppet-whatsapp@0.41 works. Will check corresponding code.

It works due to the `puppet-whatsapp` version is `0.41.198`, and the version does not contain the refactor code(something wrong when refactor).

**Comment by huan** [comment]
Thanks for the investigation!

I think there might need an integration test to make sure we can receive the `scan` event from the puppet after it start()-ed.

**Comment by huan** [comment]
Close this issue because the problem has been fixed.

Appreciate it!

**Comment by hcfw007** [comment]
I'm writing a test for qrcode, hoping it will prevent this kind of situation in the future.
