### ISSUE TITLE
Error after scan the qrcode (scaned by a multi-device enabled whatsapp account)

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-whatsapp#331]
```
22:00:50 ERR WhatsAppManager start() whatsapp.initialize() rejection: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket')
    at __puppeteer_evaluation_script__:6:62
```

Does this mean that the multi-device enabled account is not supported?

**Comment by su-chang** [comment]
> Does this mean that the multi-device enabled account is not supported?

Yes, you are right. MD will be enabled in the next step.

**Comment by su-chang** [comment]
> 22:00:50 ERR WhatsAppManager start() whatsapp.initialize() rejection: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket')
>     at __puppeteer_evaluation_script__:6:62

This error log is due to a bug which in `whatsapp-web.js`, see: https://github.com/pedroslopez/whatsapp-web.js/issues/1242 and
https://github.com/pedroslopez/whatsapp-web.js/pull/1249

I will fix it now by upgrade the dependence.

**Comment by huan** [comment]
Thank you very much for the explanation and the fixing!

**Comment by huan** [comment]
## Update: whatsappweb.js@1.16 supports Multi Device

See: https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.16.0

## Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts

However, I got the above error message because of the below change:

> the old way of passing session as a client option is now deprecated.

By trying to use the official whatsappweb.js to replace the @juzi.bot/whatsappweb.js

```sh
$ pwd
/home/huan/git/wechaty/getting-started
$ npm i whatsapp-web.js
$ cd node_modules/@juzi.bot/
$ ls
whatsapp-web.js
$ whatsapp-web.js whatsapp-web.js.bak
$ ln -s ../whatsapp-web.js .
$ ls -l
lrwxrwxrwx 1 huan huan   18 Apr  6 13:14 whatsapp-web.js -> ../whatsapp-web.js
drwxrwxr-x 3 huan huan 4096 Mar 29 13:53 whatsapp-web.js.bak
$ cd ../..
$ ls
data                            dist  examples  Makefile      NOTICE        package-lock.json  tests  tsconfig.json
ding-dong-bot.memory-card.json  docs  LICENSE   node_modules  package.json  README.md          t.js   t.ts
$ npm run start:whatsapp:web
...
13:14:40 ERR PuppetWhatsApp Manager start() whatsapp.initialize() rejection: Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
```

**Comment by huan** [comment]
`wechaty-puppet-whatsapp@1.15.7` has supported Multi Devices accounts.

Cheers!

**Comment by su-chang** [comment]
@huan Thank you for your feedback, and I will upgrade `wechaty-puppet-whatsapp@1.15.7` to be the latest version, and then it will not confuse others any more.
