### ISSUE TITLE
WhatsApp Update: Only Group Administrator can add member join the room, others cannot add any more.

### ISSUE THREAD

**Issue by lijiarui** [wechaty/puppet-whatsapp#361]
### Room Administrator 

![origin_img_v2_5c3a9477-1621-47c6-9947-ffb46326265g](https://user-images.githubusercontent.com/6419514/168960622-6f499dd4-7bb1-413a-a3e6-05edb244aa29.jpg)

### Not Room Administrator
![middle_img_v2_240fdf6a-ddb6-4848-99a8-df98a847badg](https://user-images.githubusercontent.com/6419514/168960571-a84a8c3d-81ef-402c-b698-5ffa3c7d2e55.jpg)

**Comment by hcfw007** [comment]
`Whtasapp.GroupChat.addParticipants` has a return value containing the result of this participant adding action.
examples:
```
success: {"8613126768525@c.us":200,"status":207,"participants":[{"8613126768525@c.us":{"code":"200","invite_code":null,"invite_code_exp":null}}]}
failure: {"status":401} 
failure: {"8613126768525@c.us":409,"status":207,"participants":[{"8613126768525@c.us":{"code":"409","invite_code":null,"invite_code_exp":null}}]} 
partly success: {"8613351873428@c.us":200,"8613126768525@c.us":409,"status":207,"participants":[{"8613351873428@c.us":{"code":"200","invite_code":null,"invite_code_exp":null}},{"8613126768525@c.us":{"code":"409","invite_code":null,"invite_code_exp":null}}]}
```

**Comment by hcfw007** [comment]
status code mapping (from experience)
1. overall status: 
  - 207: sucess (at least partly success); 
  - 401: failed (not admin)
2. accountId status:
  - 200: success
  - 409: already in group

**Comment by lijiarui** [comment]
Good Job！ Cheers！
