### ISSUE TITLE
cannot connect to web.whatsapp.com when restart system as logout state

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-whatsapp#367]
Steps to reproduce the problem:
1. make sure PuppetWhatsAppOptions.puppeteerOptions.puppeteer.headless is unset or truthy value.
2. start puppet and wait till qrcode appears.
3. terminate the system and restart.
4. system will stuck and no qrcode event will be triggered.

Something might be helpful:
- This might be realted to localAuth defined by whatsapp-web.js. If at first we start the system with headless as falsy, the problem will disappear. This hows that the localAuth generated by headless: off mode will prevent the problem.
- However if we start with headless on but turn it off afterwards, the problem will remain. And the browswer will say that you need to update your Chrome to 60+ (actually we have 100.0.4889.0)
- If we clear the localAuth folder, the problem will disappear.

Potential solution:
1. We set a timeout for scan or login event. If we did not receive such event in like 30 seconds, we clear the localAuth folder and try again.
2. We can save a correct session (created by starting the puppeteer in headless: off mode) in the puppet.

Update:
- Reproduced with whatsapp-web.js (just set headless to true in example.js)
- There is no silver bullets in whatsapp-web.js issue. Suggestion is delete session everytime, which is not acceptable for us here.

**Comment by hcfw007** [comment]
https://github.com/pedroslopez/whatsapp-web.js/issues/1463

**Comment by hcfw007** [comment]
@huan @su-chang Any suggestion on this?

**Comment by su-chang** [comment]
扫描已经过期的二维码提示截图如下

![origin_img_v2_d50ba0f1-8224-4610-8672-8d2b54a4f6fg](https://user-images.githubusercontent.com/9332609/169945551-76b3b4f4-6be2-43b1-bf30-8d64df5f7c34.jpg)

**Comment by lijiarui** [comment]
> 扫描已经过期的二维码提示截图如下
> 
> ![origin_img_v2_d50ba0f1-8224-4610-8672-8d2b54a4f6fg](https://user-images.githubusercontent.com/9332609/169945551-76b3b4f4-6be2-43b1-bf30-8d64df5f7c34.jpg)

How to reproduce:

- Open VPN and scan the QRCode
- After scan the QRCode, close the VPN immediately
