### ISSUE TITLE
统一error类型，确保所有异常都有对应的错误类型，引入gerror模块来实现

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#38]
统一error类型，确保所有异常都有对应的错误类型

```ts
export default class WAError extends Error {

  constructor (type: WAErrorType, message: string) {
    super(`${type} ${message}`)
  }

}
```

**Comment by huan** [comment]
Currently the `gerror` module is used with the Wechaty ecosystem, it's very simple and straightforward, read the source code of it is recommend before continue working on this issue.

GError source code: https://github.com/huan/gerror/blob/main/src/gerror/gerror.ts

**Comment by su-chang** [comment]
Thanks for your suggestions. We will try it asap.

And happy to see Wechaty ecosystem become better and better.
