### ISSUE TITLE
采用mixins的方式来实现puppet-whatsapp中的方法，并进行合理划分

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#40]
目前 wechaty-puppet 中的抽象方法较多，都需要在 puppet-whatsapp 中进行继承实现。会造成该文件中的代码篇幅过长，且不易维护和阅读。

需要将不同分类的方法通过mixins的方式进行归类。

**Comment by hcfw007** [comment]
确实，否则会导致 puppet-whatsapp，manager 这两个类特别大且重复很高
