### ISSUE TITLE
如果不开启 headless 模式，登录后 puppeteer 会自动关闭导致直接提示退出登录

### ISSUE THREAD

**Issue by su-chang** [wechaty/puppet-whatsapp#82]

**Comment by bung87** [comment]
not related to headless mode

**Comment by huan** [comment]
It would be a good practice for explaining what you have learned before closing an issue, instead just close it without any detailed information.

A good issue can inspire other developers, and help others to learn what we have learned.

**Comment by bung87** [comment]
it's duplicated with https://github.com/wechaty/puppet-whatsapp/issues/105 , details see there.

**Comment by huan** [comment]
Thank you very much for linking to the related issues!
