### ISSUE TITLE
关于好友事件的触发

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-whatsapp#87]
whatsapp-web.js未提供好友关系事件，本质上whatsapp也并没有好友关系（双向），而是可以拥有一个通讯录，只要你单向在通讯录中，就可以联系对方。在此背景下，whatsapp本身并没有好友事件的基础。
但也许可以将非好友发来的消息作为好友事件：
优点：可以正常触发好友事件，在bot端可以复用一些好有相关逻辑，然后将把对方加入通讯录视作同意好友。
缺点：可能非好友连续发多条消息导致反复推送好友事件（例如：你好？在吗？在吗？在吗）。运作关系与传统好友不同，可能会产生其他问题。

**Comment by su-chang** [comment]
补充一个案例，如果不是好友情况，bot需要在手机端或者web客户端进行选择
- 举报
- 添加到通讯录

如果不手动将其添加至通讯录，则无法监听到对应的消息事件。

**Comment by hcfw007** [comment]
19:39:26 INFO PuppetWhatsApp onMessage({"id":{"fromMe":false,"remote":"8613811286503@c.us","id":"C7B7A771964696FBE7BDB944CD100433","_serialized":"false_8613811286503@c.us_C7B7A771964696FBE7BDB944CD100433"},"ack":0,"hasMedia":false,"body":"12","type":"chat","timestamp":1643110765,"from":"8613811286503@c.us","to":"8618500946096@c.us","deviceType":"android","isForwarded":false,"forwardingScore":0,"isStatus":false,"isStarred":false,"broadcast":false,"fromMe":false,"hasQuotedMsg":false,"vCards":[],"mentionedIds":[],"links":[]})

也存在不添加好友就能触发信息的情况。此时Contact.isMyContact为false

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/puppet-whatsapp/issues/121
